version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: control_api
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/app/apps/api
      # Evitar que los node_modules locales sobrescriban los del contenedor
      - /app/apps/api/node_modules
    environment:
      - PORT=3001
    env_file:
      - ./apps/api/.env
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: control_web
    ports:
      - "3003:3003"
    volumes:
      - ./apps/web:/app/apps/web:delegated
      - /app/apps/web/node_modules
      - /app/apps/web/.next # ðŸ”¥ Evita que el .next local y el de Docker choquen
    environment:
      - PORT=3003
    env_file:
      - ./apps/web/.env.local
    depends_on:
      - api
    restart: unless-stopped
